export const GET_ALL_CASE = 'GET_ALL_CASE';
export const GET_ALL_CASE_SUCCESS = 'GET_ALL_CASE_SUCCESS';
export const GET_ALL_CASE_FAILED = 'GET_ALL_CASE_SUCCESS';
export const GET_GLOBAL_CASE = 'GET_GLOBAL_CASE';
export const GET_GLOBAL_SUCCESS = 'GET_GLOBAL_SUCCESS';
export const GET_GLOBAL_FAILED = 'GET_GLOBAL_FAILED';

export const GET_CASE_COUNTRY = 'GET_CASE_COUNTRY';